name = "revenge-next-plugs-dev"
compatibility_date = "2026-08-08"
account_id = "dc5e308f1df2d6bb5082951d3f3993a5"
main = "worker/src/index.ts"

[assets]
directory = "build/dist"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "revenge-next-plugs-dev"
database_id = "e51523c4-15d3-41c0-af5c-b7a57647450c"

[[routes]]
pattern = "dev-next.jarviscli.dev"
custom_domain = true
