// Shared Discord module ID store for plugins. Module IDs shift between Discord
// builds; they're refreshed here by scripts/update-discord-module-ids.mjs from
// lvwmwm/decord's data branch (https://github.com/lvwmwm/decord/tree/data) on the
// latest build. Module paths are stable across builds; you can add/remove entries
// here and the script only updates the IDs.

export const discordBuild = 348204

export const discordModules = {
	'modules/main_tabs_v2/native/you_bar/YouBarNotificationsButton.tsx': 16006,
	'modules/main_tabs_v2/native/you_bar/YouBarBackground.tsx': 15996,
	'modules/main_tabs_v2/native/you_bar/YouBarNameplate.tsx': 15997,
	'modules/main_tabs_v2/native/you_bar/YouBarAvatarDefault.tsx': 15999,
	'modules/main_tabs_v2/native/you_bar/YouBarAvatar.tsx': 16000,
	'modules/main_tabs_v2/native/you_bar/YouBarName.tsx': 16001,
	'modules/main_tabs_v2/native/you_bar/YouBarUser.tsx': 15998,
	'modules/main_tabs_v2/native/you_bar/YouBarButton.tsx': 16005,
	'modules/main_tabs_v2/native/you_bar/YouBarConstants.tsx': 14602,
	'modules/main_tabs_v2/native/you_bar/YouBarActivityStatusExperiment.tsx': 15980,
	'modules/main_tabs_v2/native/you_bar/YouBar.tsx': 15974,
	'modules/user_profile/native/showUserProfileActionSheet.tsx': 7617,
	'modules/user_profile/native/YouScreenUserProfileContent.tsx': 16586,
	'modules/main_tabs_v2/native/tabs/you/YouScreen.tsx': 16569,
	'modules/guilds_bar/native/GuildsBarMessages.tsx': 15918,
	'modules/guilds_bar/native/hooks/useGuildsBarProps.tsx': 15902,
	'modules/guilds_bar/native/GuildsBar.tsx': 15893,
	'modules/application_commands/ApplicationCommandQueryApi.tsx': 8711,
	'modules/application_commands/ApplicationCommandBuiltIns.tsx': 8593,
	'modules/chat_input/native/accessories/ChatInputSendUtils.tsx': 11465,
	'utils/AvatarUtils.tsx': 1397,
	'modules/action_sheet/native/ActionSheetActionCreators.tsx': 4796,
	'modules/action_sheet/native/ActionSheetStore.tsx': 4518,
	'modules/action_sheet/native/showSimpleActionSheet.tsx': 6610,
	'design/components/Sheet/native/showSimpleActionSheet.native.tsx': 6611,
	'design/components/Sheet/native/SimpleActionSheet.native.tsx': 6612,
	'design/components/Sheet/native/ActionSheet.native.tsx': 6613,
	'design/components/Sheet/native/ActionSheetRow.native.tsx': 6615,
	'modules/user_profile/native/UserProfileRolesCard.tsx': 6601,
	'modules/user_profile/UserProfileRoleUtils.tsx': 6622,
	'modules/chat/native/TypingIndicator.tsx': 11432,
	'modules/chat/useTypingUsersIds.tsx': 11434,
	'stores/TypingStore.tsx': 11433,
	'modules/chat_input/native/accessories/ChatInputCharCounter.tsx': 11904,
	'modules/chat_input/native/action_buttons/ChatInputRightActions.tsx': 11905,
	'modules/chat_input/native/guard/ChatInputGuardWrapper.tsx': 11908,
	'modules/chat_input/native/ChatInput.tsx': 11426,
	'modules/chat_input/native/ChatInputNativeCommands.tsx': 11456,
	'modules/chat_input/native/FloatingChatInputContainer.tsx': 11882,
	'stores/GuildRoleStore.tsx': 2101,
	'records/GuildRoleRecord.tsx': 2102,
	'utils/GuildRoleUtils.tsx': 2105,
	'stores/GuildMemberStore.tsx': 2107,
	'modules/guild_sidebar/native/VoiceUserNameItem.tsx': 15730,
	'modules/messages/useMessageAuthor.tsx': 5076,
	'modules/messages/createMessage.tsx': 7166,
	'modules/messages/native/renderer/getTagProperties.tsx': 7471,
	'modules/messages/native/renderer/ChatManager.tsx': 11018,
	'stores/UserStore.tsx': 1372,
	'actions/MessageActionCreators.tsx': 6871,
	'modules/gateway/GatewayConnectionStore.tsx': 5584,
	'modules/markup_v2/native/transformNativeMarkupMention.tsx': 7550,
	'actions/ModalActionCreators.tsx': 5032,
	'design/components/Navigator/native/Navigator.native.tsx': 6416,
	'design/components/Navigator/native/NavigatorHeader.native.tsx': 5931,
	'modules/messages/native/long_press/LongPressMessageActionSheet.tsx': 11139,
	'modules/messages/native/long_press/showLongPressMessageActionSheet.tsx': 11138,
	'asyncRequireImpl': 1980,
} as const
