// Shared Discord module ID store for plugins. Module IDs shift between Discord
// builds; they're refreshed here by scripts/update-discord-module-ids.mjs from
// lvwmwm/decord's data branch (https://github.com/lvwmwm/decord/tree/data) on the
// latest build. Module paths are stable across builds; you can add/remove entries
// here and the script only updates the IDs.

export const discordBuild = 348203

export const discordModules = {
	'modules/main_tabs_v2/native/you_bar/YouBarNotificationsButton.tsx': 16820,
	'modules/main_tabs_v2/native/you_bar/YouBarBackground.tsx': 16810,
	'modules/main_tabs_v2/native/you_bar/YouBarNameplate.tsx': 16811,
	'modules/main_tabs_v2/native/you_bar/YouBarAvatarDefault.tsx': 16813,
	'modules/main_tabs_v2/native/you_bar/YouBarAvatar.tsx': 16814,
	'modules/main_tabs_v2/native/you_bar/YouBarName.tsx': 16815,
	'modules/main_tabs_v2/native/you_bar/YouBarUser.tsx': 16812,
	'modules/main_tabs_v2/native/you_bar/YouBarButton.tsx': 16819,
	'modules/main_tabs_v2/native/you_bar/YouBarConstants.tsx': 15434,
	'modules/main_tabs_v2/native/you_bar/YouBarActivityStatusExperiment.tsx': 16794,
	'modules/main_tabs_v2/native/you_bar/YouBar.tsx': 16790,
	'modules/user_profile/native/showUserProfileActionSheet.tsx': 8527,
	'modules/user_profile/native/YouScreenUserProfileContent.tsx': 17371,
	'modules/main_tabs_v2/native/tabs/you/YouScreen.tsx': 17354,
	'modules/guilds_bar/native/GuildsBarMessages.tsx': 16734,
	'modules/guilds_bar/native/hooks/useGuildsBarProps.tsx': 16718,
	'modules/guilds_bar/native/GuildsBar.tsx': 16709,
	'modules/application_commands/ApplicationCommandQueryApi.tsx': 9613,
	'modules/chat_input/native/accessories/ChatInputSendUtils.tsx': 12339,
	'utils/AvatarUtils.tsx': 1397,
	'modules/action_sheet/native/ActionSheetActionCreators.tsx': 4796,
	'modules/action_sheet/native/ActionSheetStore.tsx': 4516,
	'modules/action_sheet/native/showSimpleActionSheet.tsx': 7527,
	'design/components/Sheet/native/showSimpleActionSheet.native.tsx': 7528,
	'design/components/Sheet/native/SimpleActionSheet.native.tsx': 7529,
	'design/components/Sheet/native/ActionSheet.native.tsx': 7530,
	'design/components/Sheet/native/ActionSheetRow.native.tsx': 7532,
	'modules/user_profile/native/UserProfileRolesCard.tsx': 7518,
	'modules/user_profile/UserProfileRoleUtils.tsx': 7539,
	'modules/chat/native/TypingIndicator.tsx': 12306,
	'modules/chat/useTypingUsersIds.tsx': 12308,
	'stores/TypingStore.tsx': 12307,
	'modules/chat_input/native/accessories/ChatInputCharCounter.tsx': 12778,
	'modules/chat_input/native/action_buttons/ChatInputRightActions.tsx': 12779,
	'modules/chat_input/native/guard/ChatInputGuardWrapper.tsx': 12782,
	'modules/chat_input/native/ChatInput.tsx': 12300,
	'modules/chat_input/native/ChatInputNativeCommands.tsx': 12330,
	'modules/chat_input/native/FloatingChatInputContainer.tsx': 12756,
	'stores/GuildRoleStore.tsx': 2101,
	'records/GuildRoleRecord.tsx': 2102,
	'utils/GuildRoleUtils.tsx': 2105,
	'stores/GuildMemberStore.tsx': 2107,
	'modules/guild_sidebar/native/VoiceUserNameItem.tsx': 16550,
	'modules/messages/useMessageAuthor.tsx': 5075,
	'modules/messages/createMessage.tsx': 8081,
	'modules/messages/native/renderer/getTagProperties.tsx': 8382,
	'modules/messages/native/renderer/ChatManager.tsx': 11875,
	'stores/UserStore.tsx': 1372,
	'actions/MessageActionCreators.tsx': 7786,
	'modules/gateway/GatewayConnectionStore.tsx': 5582,
	'modules/markup_v2/native/transformNativeMarkupMention.tsx': 8460,
	'asyncRequireImpl': 1980,
} as const
