// Shared Discord module ID store for plugins. Module IDs shift between Discord
// builds; they're refreshed here by scripts/update-discord-module-ids.mjs from
// lvwmwm/decord's data branch (https://github.com/lvwmwm/decord/tree/data) on the
// latest build. Module paths are stable across builds; you can add/remove entries
// here and the script only updates the IDs.

export const discordBuild = 348200

export const discordModules = {
	'modules/main_tabs_v2/native/you_bar/YouBarNotificationsButton.tsx': 16732,
	'modules/main_tabs_v2/native/you_bar/YouBarBackground.tsx': 16722,
	'modules/main_tabs_v2/native/you_bar/YouBarNameplate.tsx': 16723,
	'modules/main_tabs_v2/native/you_bar/YouBarAvatarDefault.tsx': 16725,
	'modules/main_tabs_v2/native/you_bar/YouBarAvatar.tsx': 16726,
	'modules/main_tabs_v2/native/you_bar/YouBarName.tsx': 16727,
	'modules/main_tabs_v2/native/you_bar/YouBarUser.tsx': 16724,
	'modules/main_tabs_v2/native/you_bar/YouBarButton.tsx': 16731,
	'modules/main_tabs_v2/native/you_bar/YouBarConstants.tsx': 15365,
	'modules/main_tabs_v2/native/you_bar/YouBarActivityStatusExperiment.tsx': 16706,
	'modules/main_tabs_v2/native/you_bar/YouBar.tsx': 16702,
	'modules/user_profile/native/showUserProfileActionSheet.tsx': 8448,
	'modules/user_profile/native/YouScreenUserProfileContent.tsx': 17267,
	'modules/main_tabs_v2/native/tabs/you/YouScreen.tsx': 17250,
	'modules/guilds_bar/native/GuildsBarMessages.tsx': 16647,
	'modules/guilds_bar/native/hooks/useGuildsBarProps.tsx': 16631,
	'modules/guilds_bar/native/GuildsBar.tsx': 16622,
	'modules/application_commands/ApplicationCommandQueryApi.tsx': 9530,
	'modules/chat_input/native/accessories/ChatInputSendUtils.tsx': 12250,
	'utils/AvatarUtils.tsx': 1397,
	'modules/action_sheet/native/ActionSheetActionCreators.tsx': 4723,
	'modules/action_sheet/native/ActionSheetStore.tsx': 4447,
	'modules/action_sheet/native/showSimpleActionSheet.tsx': 7439,
	'design/components/Sheet/native/showSimpleActionSheet.native.tsx': 7440,
	'design/components/Sheet/native/SimpleActionSheet.native.tsx': 7441,
	'design/components/Sheet/native/ActionSheet.native.tsx': 7442,
	'design/components/Sheet/native/ActionSheetRow.native.tsx': 7444,
	'modules/user_profile/native/UserProfileRolesCard.tsx': 7430,
	'modules/user_profile/UserProfileRoleUtils.tsx': 7451,
	'modules/chat/native/TypingIndicator.tsx': 12217,
	'modules/chat/useTypingUsersIds.tsx': 12219,
	'stores/TypingStore.tsx': 12218,
	'modules/chat_input/native/accessories/ChatInputCharCounter.tsx': 12683,
	'modules/chat_input/native/action_buttons/ChatInputRightActions.tsx': 12684,
	'modules/chat_input/native/guard/ChatInputGuardWrapper.tsx': 12687,
	'modules/chat_input/native/ChatInput.tsx': 12211,
	'modules/chat_input/native/ChatInputNativeCommands.tsx': 12241,
	'modules/chat_input/native/FloatingChatInputContainer.tsx': 12661,
	'stores/GuildRoleStore.tsx': 2099,
	'records/GuildRoleRecord.tsx': 2100,
	'utils/GuildRoleUtils.tsx': 2103,
	'stores/GuildMemberStore.tsx': 2105,
	'modules/guild_sidebar/native/VoiceUserNameItem.tsx': 16463,
	'modules/messages/useMessageAuthor.tsx': 4988,
	'modules/messages/createMessage.tsx': 7994,
	'modules/messages/native/renderer/getTagProperties.tsx': 8292,
	'modules/messages/native/renderer/ChatManager.tsx': 11789,
	'stores/UserStore.tsx': 1372,
	'actions/MessageActionCreators.tsx': 7698,
	'modules/gateway/GatewayConnectionStore.tsx': 5494,
	'modules/markup_v2/native/transformNativeMarkupMention.tsx': 8370,
	'asyncRequireImpl': 1980,
} as const
