/**
 * Best-effort mapping from Discord's pre-redesign semantic color names (used by most
 * existing Bunny/Vendetta theme specs) to the current "redesign" token names. There is no
 * official alias table shipped in the app - this is a hand-built approximation based on the
 * two schemes' semantics, so coverage is partial, not exhaustive.
 */
export const LEGACY_ALIASES: Record<string, string | string[]> = {
	BACKGROUND_PRIMARY: 'BACKGROUND_BASE_LOWEST',
	BACKGROUND_SECONDARY: 'BACKGROUND_BASE_LOWER',
	BACKGROUND_TERTIARY: 'BACKGROUND_BASE_LOW',
	BACKGROUND_MOBILE_PRIMARY: 'BACKGROUND_BASE_LOWEST',
	BACKGROUND_MOBILE_SECONDARY: 'BACKGROUND_BASE_LOWER',
	BACKGROUND_FLOATING: 'BACKGROUND_SURFACE_HIGH',
	BACKGROUND_NESTED_FLOATING: 'BACKGROUND_SURFACE_HIGHEST',
	BACKGROUND_MODIFIER_HOVER: 'BACKGROUND_MOD_SUBTLE',
	BACKGROUND_MODIFIER_ACTIVE: 'BACKGROUND_MOD_NORMAL',
	BACKGROUND_MODIFIER_SELECTED: 'BACKGROUND_MOD_STRONG',
	BACKGROUND_MODIFIER_ACCENT: 'BACKGROUND_MOD_MUTED',
	BACKGROUND_MODIFIER_ACCEPT: 'BACKGROUND_FEEDBACK_POSITIVE',
	BACKGROUND_MODIFIER_ACCEPT_HOVER: 'BACKGROUND_FEEDBACK_POSITIVE',
	BACKGROUND_MENTIONED: 'MENTION_BACKGROUND',
	BACKGROUND_MENTIONED_HOVER: 'MENTION_BACKGROUND',
	BACKGROUND_MESSAGE_HOVER: 'MESSAGE_BACKGROUND_HOVER',
	CHAT_BACKGROUND: 'BACKGROUND_BASE_LOWEST',
	HOME_BACKGROUND: 'BACKGROUND_BASE_LOWER',
	KEYBOARD: 'MOBILE_KEYBOARD_PANEL_BACKGROUND',
	BG_BASE_PRIMARY: 'BACKGROUND_BASE_LOWEST',
	BG_BASE_SECONDARY: 'BACKGROUND_BASE_LOWER',
	BG_BASE_TERTIARY: 'BACKGROUND_BASE_LOW',
	BG_BACKDROP: 'BACKGROUND_SCRIM',
	BG_MOD_FAINT: 'BACKGROUND_MOD_SUBTLE',
	BG_SURFACE_OVERLAY_TMP: 'BACKGROUND_SURFACE_HIGH',
	BORDER_FAINT: 'BORDER_SUBTLE',
	ELEVATION_HIGH: 'BACKGROUND_SURFACE_HIGH',
	ELEVATION_LOW: 'BACKGROUND_BASE_LOW',
	ELEVATION_MEDIUM: 'BACKGROUND_BASE_LOWER',
	ELEVATION_STROKE: 'BORDER_SUBTLE',
	FOCUS_PRIMARY: 'BORDER_FOCUS',

	TEXT_NORMAL: 'TEXT_DEFAULT',
	TEXT_PRIMARY: 'TEXT_DEFAULT',
	TEXT_SECONDARY: 'TEXT_SUBTLE',
	HEADER_PRIMARY: 'MOBILE_TEXT_HEADING_PRIMARY',
	HEADER_SECONDARY: 'TEXT_SUBTLE',
	TEXT_DANGER: 'TEXT_FEEDBACK_CRITICAL',
	TEXT_POSITIVE: 'TEXT_FEEDBACK_POSITIVE',
	TEXT_WARNING: 'TEXT_FEEDBACK_WARNING',
	TEXT_LINK_LOW_SATURATION: 'TEXT_LINK',
	CHANNEL_TEXT_AREA_PLACEHOLDER: 'INPUT_PLACEHOLDER_TEXT_DEFAULT',

	INTERACTIVE_NORMAL: ['INTERACTIVE_TEXT_DEFAULT', 'INTERACTIVE_ICON_DEFAULT'],
	INTERACTIVE_HOVER: ['INTERACTIVE_TEXT_HOVER', 'INTERACTIVE_ICON_HOVER'],
	INTERACTIVE_ACTIVE: ['INTERACTIVE_TEXT_ACTIVE', 'INTERACTIVE_ICON_ACTIVE'],

	INPUT_BACKGROUND: 'INPUT_BACKGROUND_DEFAULT',
	CARD_PRIMARY_BG: 'CARD_BACKGROUND_DEFAULT',
	DEPRECATED_CARD_BG: 'CARD_BACKGROUND_DEFAULT',
	DEPRECATED_CARD_EDITABLE_BG: 'CARD_BACKGROUND_DEFAULT',
	DEPRECATED_TEXT_INPUT_BG: 'INPUT_BACKGROUND_DEFAULT',
	DEPRECATED_TEXT_INPUT_BORDER: 'INPUT_BORDER_DEFAULT',
	DEPRECATED_TEXT_INPUT_BORDER_DISABLED: 'INPUT_BORDER_DEFAULT',
	DEPRECATED_TEXT_INPUT_BORDER_HOVER: 'INPUT_BORDER_ACTIVE',
	DEPRECATED_TEXT_INPUT_PREFIX: 'INPUT_PLACEHOLDER_TEXT_DEFAULT',
	DEPRECATED_QUICKSWITCHER_INPUT_BACKGROUND: 'MOBILE_COMMAND_BAR_BACKGROUND',
	DEPRECATED_QUICKSWITCHER_INPUT_PLACEHOLDER: 'INPUT_PLACEHOLDER_TEXT_DEFAULT',
	DEPRECATED_STORE_BG: 'BACKGROUND_BASE_LOWEST',

	ANDROID_RIPPLE: 'MOBILE_ANDROID_BUTTON_BACKGROUND_RIPPLE',
	TYPING_INDICATOR_BG: 'MOBILE_TYPING_INDICATOR_BACKGROUND_DEFAULT',
	EXPRESSION_PICKER_BG: 'MOBILE_EXPRESSION_PICKER_BACKGROUND_DEFAULT',

	INFO_DANGER_BACKGROUND: 'BACKGROUND_FEEDBACK_CRITICAL',
	INFO_DANGER_TEXT: 'TEXT_FEEDBACK_CRITICAL',
	INFO_DANGER_FOREGROUND: 'TEXT_FEEDBACK_CRITICAL',
	INFO_WARNING_BACKGROUND: 'BACKGROUND_FEEDBACK_WARNING',
	INFO_WARNING_TEXT: 'TEXT_FEEDBACK_WARNING',
	INFO_WARNING_FOREGROUND: 'TEXT_FEEDBACK_WARNING',
	INFO_POSITIVE_BACKGROUND: 'BACKGROUND_FEEDBACK_POSITIVE',
	INFO_POSITIVE_TEXT: 'TEXT_FEEDBACK_POSITIVE',
	INFO_POSITIVE_FOREGROUND: 'TEXT_FEEDBACK_POSITIVE',
	INFO_HELP_BACKGROUND: 'BACKGROUND_FEEDBACK_INFO',
	INFO_HELP_TEXT: 'TEXT_FEEDBACK_INFO',
	INFO_HELP_FOREGROUND: 'TEXT_FEEDBACK_INFO',

	STATUS_DANGER_BACKGROUND: 'STATUS_DANGER',
	STATUS_DANGER_TEXT: 'TEXT_FEEDBACK_CRITICAL',

	REDESIGN_BUTTON_SECONDARY_BACKGROUND: 'REDESIGN_BUTTON_TERTIARY_BACKGROUND',
	REDESIGN_BUTTON_SECONDARY_ALT_BACKGROUND: 'REDESIGN_BUTTON_TERTIARY_BACKGROUND',
	REDESIGN_BUTTON_DANGER_BACKGROUND: 'STATUS_DANGER',
	REDESIGN_CHANNEL_CATEGORY_NAME_TEXT: 'REDESIGN_CHANNEL_NAME_MUTED_TEXT',
	REDESIGN_ACTIVITY_CARD_BACKGROUND_PRESSED: 'REDESIGN_IMAGE_BUTTON_PRESSED_BACKGROUND',

	CHAT_SWIPE_TO_REPLY_BACKGROUND: 'BACKGROUND_MOD_SUBTLE',
	ACTIVITY_CARD_BACKGROUND: 'CARD_BACKGROUND_DEFAULT',
	REDESIGN_ACTIVITY_CARD_BACKGROUND: 'CARD_BACKGROUND_DEFAULT',
	FORUM_POST_TAG_BACKGROUND: 'BADGE_BACKGROUND_DEFAULT',
	REDESIGN_BUTTON_SECONDARY_BORDER: 'BORDER_SUBTLE',
	POLLS_NORMAL_FILL_HOVER: 'BACKGROUND_MOD_SUBTLE',
	TEXTBOX_MARKDOWN_SYNTAX: 'TEXT_MUTED',
	LOGO_PRIMARY: 'TEXT_BRAND',
	GUILD_HEADER_TEXT_SHADOW: 'BACKGROUND_SCRIM',
	BUG_REPORTER_MODAL_SUBMITTING_BACKGROUND: 'MODAL_BACKGROUND',
	AUTOMOD_QUEUED_FOR_REVIEW_BACKGROUND: 'BACKGROUND_FEEDBACK_WARNING',
	AUTOMOD_QUEUED_FOR_REVIEW_BACKGROUND_HOVER: 'BACKGROUND_FEEDBACK_WARNING',
}

export function resolveLegacyAliases(name: string): string[] {
	const alias = LEGACY_ALIASES[name]
	if (!alias) return []
	return Array.isArray(alias) ? alias : [alias]
}
