import type { ClydePreset } from './types'

export const PRESETS: ClydePreset[] = [
	{
		id: 'clyde',
		name: 'Clyde',
		avatar: 'https://cdn.discordapp.com/embed/avatars/0.png',
		banner: '',
		bio: "I'm your friendly Discord bot companion!",
		tagText: 'APP',
		tagTextColor: '#FFFFFF',
		tagBackgroundColor: '#5865F2',
		tagVerified: true,
		color: '#5865F2',
	},
	{
		id: 'chatgpt',
		name: 'ChatGPT',
		avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png',
		banner: '',
		bio: 'OpenAI intelligent conversational AI model.',
		tagText: 'AI',
		tagTextColor: '#FFFFFF',
		tagBackgroundColor: '#10A37F',
		tagVerified: true,
		color: '#10A37F',
	},
	{
		id: 'claude',
		name: 'Claude',
		avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Anthropic_logo.svg/512px-Anthropic_logo.svg.png',
		banner: '',
		bio: 'Anthropic AI assistant focused on helpful and honest guidance.',
		tagText: 'CLAUDE',
		tagTextColor: '#FFFFFF',
		tagBackgroundColor: '#D97706',
		tagVerified: true,
		color: '#D97706',
	},
	{
		id: 'gemini',
		name: 'Gemini',
		avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Google_Gemini_logo.svg/512px-Google_Gemini_logo.svg.png',
		banner: '',
		bio: 'Google DeepMind state-of-the-art multimodal AI.',
		tagText: 'GEMINI',
		tagTextColor: '#FFFFFF',
		tagBackgroundColor: '#4285F4',
		tagVerified: true,
		color: '#4285F4',
	},
	{
		id: 'jarvis',
		name: 'JARVIS',
		avatar: 'https://cdn.discordapp.com/embed/avatars/1.png',
		banner: '',
		bio: 'Just A Rather Very Intelligent System. At your service, sir.',
		tagText: 'SYSTEM',
		tagTextColor: '#000000',
		tagBackgroundColor: '#00E5FF',
		tagVerified: true,
		color: '#00E5FF',
	},
	{
		id: 'gigaclyde',
		name: 'GigaClyde',
		avatar: 'https://cdn.discordapp.com/embed/avatars/4.png',
		banner: '',
		bio: '🗿 Absolute perfection. Unmatched AI charisma.',
		tagText: 'GIGA',
		tagTextColor: '#000000',
		tagBackgroundColor: '#F1C40F',
		tagVerified: true,
		color: '#F1C40F',
	},
]
